/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ads.presentation;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author MFA
 */
public class AdminCreateFloorMapView extends javax.swing.JFrame {
    private final ClientControllerInterface controller;
    /**
     * Creates new form AdminCreateFloorMapView
     */
    public AdminCreateFloorMapView()
    {
        initComponents();
        controller=null;
    }
    public AdminCreateFloorMapView(ClientControllerInterface c) {
        initComponents();
        controller = c;
        
        floorMapPanel.setBackground(Color.WHITE);
        drawFloorMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorMapPanel = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g)   {
                // Paint background
                super.paintComponent(g);

                // Get the drawing area
                int dy = getSize ().height;
                int dx = getSize ().width;
                int mid_y = dy/2;
                int mid_x = dx/2;
                int rect_x = 3 * dx/4;
                int rect_y = 3 * dy/4;

                // Set current drawing color
                g.setColor (Color.BLACK);

                // Draw a rectangle centered at the mid-point
                g.drawRect (mid_x-rect_x/2, mid_y-rect_y/2,  rect_x, rect_y );

                // Set a new drawing color
                g.setColor (Color.LIGHT_GRAY);

                // Fill a rectangle centered at the mid-point. Put it
                // within the previous rectangle so that border shows.
                g.fillRect (mid_x-rect_x/2 + 10, mid_y-rect_y/2+10, rect_x-20, rect_y-20);

                // Set a new drawing color
                g.setColor (Color.DARK_GRAY);

                // Draw a circle around the mid-point
                g.drawOval (mid_x-rect_x/6, mid_y-rect_y/6, rect_x/3, rect_y/3);

                // Fill an oval inside the circle
                g.fillOval (mid_x-rect_x/6+10, mid_y-rect_y/6+10, rect_x/3-20, rect_y/3-20);
            } // paintComponent
        };
        floorMapPanel = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g)   {
                // Paint background
                super.paintComponent(g);

                // Get the drawing area
                int dy = getSize ().height;
                int dx = getSize ().width;
                int mid_y = dy/2;
                int mid_x = dx/2;
                int rect_x = 3 * dx/4;
                int rect_y = 3 * dy/4;

                // Set current drawing color
                g.setColor (Color.BLACK);

                // Draw a rectangle centered at the mid-point
                g.drawRect (mid_x-rect_x/2, mid_y-rect_y/2,  rect_x, rect_y );

                // Set a new drawing color
                g.setColor (Color.LIGHT_GRAY);

                // Fill a rectangle centered at the mid-point. Put it
                // within the previous rectangle so that border shows.
                g.fillRect (mid_x-rect_x/2 + 10, mid_y-rect_y/2+10, rect_x-20, rect_y-20);

                // Set a new drawing color
                g.setColor (Color.DARK_GRAY);

                // Draw a circle around the mid-point
                g.drawOval (mid_x-rect_x/6, mid_y-rect_y/6, rect_x/3, rect_y/3);

                // Fill an oval inside the circle
                g.fillOval (mid_x-rect_x/6+10, mid_y-rect_y/6+10, rect_x/3-20, rect_y/3-20);
            } // paintComponent
        };
        createMap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterMapTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout floorMapPanelLayout = new javax.swing.GroupLayout(floorMapPanel);
        floorMapPanel.setLayout(floorMapPanelLayout);
        floorMapPanelLayout.setHorizontalGroup(
            floorMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        floorMapPanelLayout.setVerticalGroup(
            floorMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        createMap.setText("Create Map");
        createMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMapActionPerformed(evt);
            }
        });

        enterMapTA.setColumns(20);
        enterMapTA.setRows(5);
        jScrollPane1.setViewportView(enterMapTA);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Sample Map Creation Code:\nnode1/adjNode,dir,dist|adjNode,dir,dist\nnode2/adjNode,dir,dist\nnode1/adjNode,dir,dist|adjNode,dir,dist|adjNode,dir,dist");
        jScrollPane3.setViewportView(jTextArea2);
        jTextArea2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(floorMapPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createMap)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(floorMapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMapActionPerformed
        String temp=enterMapTA.getText();
        System.out.println(temp);
    }//GEN-LAST:event_createMapActionPerformed

    public void drawFloorMap(){
        
    }
    //Temporary main
    public static void main(String[] arasdas)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCreateFloorMapView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createMap;
    private javax.swing.JTextArea enterMapTA;
    private javax.swing.JPanel floorMapPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
