GRANT ALL PRIVILEGES ON *.* TO 'ads'@'%' IDENTIFIED BY 'adspassword' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'ads'@'localhost' IDENTIFIED BY 'adspassword' WITH GRANT OPTION;
DROP DATABASE IF EXISTS ads;
CREATE DATABASE IF NOT EXISTS ads;
